# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FreeFood' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod ‘SwiftyJSON’

  # Pods for FreeFood

  target 'FreeFoodTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FreeFoodUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
